Django ORM pratice 오전 & some Question
rgpkr-tech-intern-1st/KimSoungRyoulRepo pull request #4
Opened 2018-09-12 03:31 UTC by KimSoungRyoul

### 1.장고에는 OneToMan	ManyToMany 	OneToOne 이 있는데 ManyToOne 이 없네요
	‘Many’ 쪽에서 필드를 가지고싶으면 ForigenKey로 해주면 되는것이 맞나요?
         ex: 하나의 회원은 여러개의 마일리지 기록을 가질수있다.   
         이때  (Many) class Mileage 에 User를 필드로 가지고 싶다.
        user = models.ForeignKey(User, on_delete=models.CASCADE)    
         이렇게하면되나요?

### 2. model 에서는 user 이지만  테이블에서 외래키의 이름을 따로 지정해줄수는 없나요? 
      ex : 모델 변수명은 user  테이블 외래키 변수명은 user_owner_id

### 3. answer = Model의 기본키에 대한 설정이 따로 없으면 장고는 자기가알아서 id를 만든다 ? True : False
       ' >> answer

### 4.  User 와 MemberInfo관계를  SuperType SubType 으로 모델링 하고 싶은데 이 경우 제가 작업한 방식이 맞나요?

2018-09-12 03:39 UTC, kucuny commented
1. `ManyToMany` 를 마이그레이션 했을 때 어떻게 테이블이 생성되는지 보시면 될 것 같습니다.
2. `db_column` 을 사용하면 됩니다.
3. `primary_key=True` 가 없는 경우 `AutoField()` 로 자동으로 만들어 줍니다.
(https://docs.djangoproject.com/ko/2.1/ref/models/fields/#django.db.models.AutoField)
4. 네

2018-09-12 03:44 UTC, kucuny requested changes

2018-09-12 03:44 UTC, kucuny commented on user_mgt/models.py
> +    mileage_amount = models.IntegerField(null=False)
최초 생성일, 업데이트 일시 등이 기록될 수 있는 필드가 추가되면 좋을 것 같네요.
또한 마일리지가 음수로 표현될 필요가 없으면 `PositiveIntegerField()`를 사용해 보세요.

2018-09-12 06:20 UTC, KimSoungRyoul commented on user_mgt/models.py
> +    mileage_amount = models.IntegerField(null=False)
감사합니다 !  다음번 커밋에 반영하겠습니다

2018-09-12 06:21 UTC, merged

2018-09-13 02:17 UTC, kucuny commented
@KimSoungRyoul 이슈제기가 된 것은 코드리뷰 대상이 되는 PR에서 모두 이루어져야 합니다. 다음 커밋에 반영한다고 해도 제가 추적할 수 없습니다. (다시 또 코드를 봐야하는..)
PR이 머지 되기 전까지 해결이 되지않은 또는 충분히 의사결정이 되지 않으면 머지하지 말아주세요.